### ISSUE TITLE
arch-android-devel

### ISSUE THREAD

**Issue by julianxhokaxhiu** [binhex/arch-devel#1]
Hi,

I saw that you created this Docker which is awesome! I was thinking, would be really awesome if you could provide a base docker image, based on Arch that provides all the basics to build a pure AOSP Android source code, with VOLUME support so we don't need to initialize the Source code inside of the Docker itself.

Related to dependencies you can take a look at https://wiki.archlinux.org/index.php/android#Building_Android

Thank you very much in advance,
Julian

**Comment by binhex** [comment]
Hi Julian, this particular image is made purely for my convenience so that i can easily test install procedure for new applications pulled either from the official arch repo or from AUR, it isn't really for a specific use case (such as android dev). Having said that you could easily fork this and include the required dependancies, looking at the link above it was be trivial to add in the required packages via the install.sh script, good luck!.

**Comment by julianxhokaxhiu** [comment]
Thank you very much, I'll go for the fork then :)
